pipeline {
    agent any
    stages {
        stage('Test DataRobot Connectivity') {
            steps {
                withCredentials([string(credentialsId: 'c88d7131-ddc1-4686-81a7-70e7724c8979', variable: 'drapikey')]) {
                    sh 'curl -XGET  https://app.datarobot.com/api/v2/users/ -H "Authorization: bearer $drapikey"'
                }
                sh 'echo "HELLO WORLD"'
            }
        }
    }
}
