pipeline {
    agent any
    stages {
        stage('DRUM Testing') {
            steps {
                sh 'drum --version'
            }
        }
        stage('Upload Custom Model Artifacts') {
            steps {
                withCredentials([string(credentialsId: 'c88d7131-ddc1-4686-81a7-70e7724c8979', variable: 'drapikey')]) {
                    sh 'curl -XGET  https://app.datarobot.com/api/v2/users/ -H "Authorization: bearer $drapikey"'
                }
                sh '''
                    pwd
                    ls -lrat
                '''
            }
        }
        stage('Perform API Testing'){
            steps {
                sh 'curl ifconfig.me'
            }
        }
    }
}
