pipeline {
    agent any
    stages {
        stage('Test DataRobot Connectivity') {
            steps {
                withCredentials([string(credentialsId: 'c88d7131-ddc1-4686-81a7-70e7724c8979', variable: 'drapikey')]) {
                    sh 'echo $drapikey'
                }
                sh 'echo "HELLO WORLD"'
            }
        }
    }
}
